spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/college_mate
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.35.111:3306/college_mate
    username: college_mate
    password: college_mate1!
